import type { SeedData } from "./types";

export const seedDemoData: SeedData = {
  tasks: [
    {
      id: "task-focus-brief",
      title: "今日の実行軸を 1 行にする",
      description: "迷いを消すための最小整理。",
      status: "pending",
      parentTaskId: null,
      effortEstimate: 2,
      urgency: 5,
      impact: 5,
      penaltyOfDelay: 5,
      momentumGain: 5,
      emotionalResistance: 1,
      energyRequired: 2,
      dueAt: null,
      createdAt: "2026-04-30T09:00:00.000Z",
      updatedAt: "2026-04-30T09:00:00.000Z",
    },
    {
      id: "task-db-persist",
      title: "タスク保存を SQLite に接続する",
      description: "seed から本データへ移す。",
      status: "pending",
      parentTaskId: null,
      effortEstimate: 3,
      urgency: 4,
      impact: 5,
      penaltyOfDelay: 4,
      momentumGain: 5,
      emotionalResistance: 2,
      energyRequired: 3,
      dueAt: null,
      createdAt: "2026-04-30T09:12:00.000Z",
      updatedAt: "2026-04-30T09:12:00.000Z",
    },
    {
      id: "task-now-copy",
      title: "Now 画面の文をさらに削る",
      description: "読む前にわかる画面へ寄せる。",
      status: "in_progress",
      parentTaskId: null,
      effortEstimate: 2,
      urgency: 4,
      impact: 4,
      penaltyOfDelay: 3,
      momentumGain: 4,
      emotionalResistance: 1,
      energyRequired: 2,
      dueAt: null,
      createdAt: "2026-04-30T10:05:00.000Z",
      updatedAt: "2026-04-30T10:40:00.000Z",
    },
    {
      id: "task-theme-polish",
      title: "白と黒の密度を整える",
      description: "緑は注意の場所だけに置く。",
      status: "pending",
      parentTaskId: null,
      effortEstimate: 2,
      urgency: 3,
      impact: 4,
      penaltyOfDelay: 3,
      momentumGain: 4,
      emotionalResistance: 1,
      energyRequired: 2,
      dueAt: null,
      createdAt: "2026-04-30T10:24:00.000Z",
      updatedAt: "2026-04-30T10:24:00.000Z",
    },
    {
      id: "task-notes-drizzle",
      title: "Drizzle のノートを作る",
      description: "DB まわりの怖さを下げる。",
      status: "pending",
      parentTaskId: null,
      effortEstimate: 2,
      urgency: 2,
      impact: 3,
      penaltyOfDelay: 2,
      momentumGain: 3,
      emotionalResistance: 2,
      energyRequired: 2,
      dueAt: null,
      createdAt: "2026-04-30T11:00:00.000Z",
      updatedAt: "2026-04-30T11:00:00.000Z",
    },
    {
      id: "task-history-reward",
      title: "完了後の返りを気持ちよくする",
      description: "履歴を自信に変える。",
      status: "pending",
      parentTaskId: null,
      effortEstimate: 3,
      urgency: 3,
      impact: 5,
      penaltyOfDelay: 3,
      momentumGain: 5,
      emotionalResistance: 2,
      energyRequired: 3,
      dueAt: null,
      createdAt: "2026-04-30T11:35:00.000Z",
      updatedAt: "2026-04-30T11:35:00.000Z",
    },
    {
      id: "task-clean-bridge",
      title: "BRIDGE の判断軸を短くする",
      description: "迷った時に戻れる形へ。",
      status: "done",
      parentTaskId: null,
      effortEstimate: 2,
      urgency: 3,
      impact: 4,
      penaltyOfDelay: 2,
      momentumGain: 4,
      emotionalResistance: 1,
      energyRequired: 2,
      dueAt: null,
      createdAt: "2026-04-29T15:15:00.000Z",
      updatedAt: "2026-04-29T16:05:00.000Z",
    },
    {
      id: "task-review-font",
      title: "フォントの見え方を確認する",
      description: "日本語と英語の差をならす。",
      status: "done",
      parentTaskId: null,
      effortEstimate: 1,
      urgency: 2,
      impact: 3,
      penaltyOfDelay: 1,
      momentumGain: 3,
      emotionalResistance: 1,
      energyRequired: 1,
      dueAt: null,
      createdAt: "2026-04-29T17:10:00.000Z",
      updatedAt: "2026-04-29T17:30:00.000Z",
    },
  ],
  events: [
    {
      id: "event-clean-bridge-created",
      taskId: "task-clean-bridge",
      eventType: "created",
      payloadJson: "{}",
      createdAt: "2026-04-29T15:15:00.000Z",
    },
    {
      id: "event-clean-bridge-completed",
      taskId: "task-clean-bridge",
      eventType: "completed",
      payloadJson: "{}",
      createdAt: "2026-04-29T16:05:00.000Z",
    },
    {
      id: "event-review-font-created",
      taskId: "task-review-font",
      eventType: "created",
      payloadJson: "{}",
      createdAt: "2026-04-29T17:10:00.000Z",
    },
    {
      id: "event-review-font-completed",
      taskId: "task-review-font",
      eventType: "completed",
      payloadJson: "{}",
      createdAt: "2026-04-29T17:30:00.000Z",
    },
    {
      id: "event-now-copy-started",
      taskId: "task-now-copy",
      eventType: "started",
      payloadJson: "{}",
      createdAt: "2026-04-30T10:40:00.000Z",
    },
  ],
};
