import type { SeedData } from "./types";

export const seedDemoData: SeedData = {
  tasks: [
    {
      id: "task-ooda-capture",
      title: "朝の気がかりを Observe に置く",
      status: "observe",
      parentTaskId: null,
      observeMemo: "考える前に置くだけにする。",
      orientMemo: "",
      roiScore: null,
      estimatedMinutes: null,
      actStartedAt: null,
      actDueAt: null,
      progressNote: "",
      createdAt: "2026-05-05T00:10:00.000Z",
      updatedAt: "2026-05-05T00:10:00.000Z",
    },
    {
      id: "task-tax-orient",
      title: "申告資料の抜けを洗い出す",
      status: "orient",
      parentTaskId: null,
      observeMemo: "抜けだけ先に見たい。",
      orientMemo: "短く確認する。",
      roiScore: 5,
      estimatedMinutes: 40,
      actStartedAt: null,
      actDueAt: null,
      progressNote: "",
      createdAt: "2026-05-05T02:00:00.000Z",
      updatedAt: "2026-05-05T02:30:00.000Z",
    },
    {
      id: "task-landing-act",
      title: "トップ画面の余白を詰める",
      status: "orient",
      parentTaskId: null,
      observeMemo: "視線が散る箇所を先に抑える。",
      orientMemo: "短く触って整える。",
      roiScore: 4,
      estimatedMinutes: 25,
      actStartedAt: null,
      actDueAt: null,
      progressNote: "",
      createdAt: "2026-05-06T08:10:00.000Z",
      updatedAt: "2026-05-06T08:40:00.000Z",
    },
    {
      id: "task-clean-done",
      title: "観測メモの文量を減らす",
      status: "done",
      parentTaskId: null,
      observeMemo: "説明でなく配置で伝える方向に寄せた。",
      orientMemo: "短い文だけ残す。",
      roiScore: 3,
      estimatedMinutes: 20,
      actStartedAt: "2026-05-04T12:00:00.000Z",
      actDueAt: "2026-05-04T12:20:00.000Z",
      progressNote: "完了。",
      createdAt: "2026-05-04T11:00:00.000Z",
      updatedAt: "2026-05-04T12:18:00.000Z",
    },
  ],
  events: [
    {
      id: "event-tax-created",
      taskId: "task-tax-orient",
      eventType: "created",
      payloadJson: "{}",
      createdAt: "2026-05-05T02:00:00.000Z",
    },
    {
      id: "event-tax-oriented",
      taskId: "task-tax-orient",
      eventType: "oriented",
      payloadJson: "{\"roiScore\":5}",
      createdAt: "2026-05-05T02:30:00.000Z",
    },
    {
      id: "event-landing-decided",
      taskId: "task-landing-act",
      eventType: "decided",
      payloadJson: "{}",
      createdAt: "2026-05-06T08:58:00.000Z",
    },
    {
      id: "event-landing-started",
      taskId: "task-landing-act",
      eventType: "act_started",
      payloadJson: "{\"estimatedMinutes\":25}",
      createdAt: "2026-05-06T09:00:00.000Z",
    },
    {
      id: "event-clean-completed",
      taskId: "task-clean-done",
      eventType: "completed",
      payloadJson: "{}",
      createdAt: "2026-05-04T12:18:00.000Z",
    },
  ],
};
